version: '3.1'

services:

  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/:ro"
